### ISSUE TITLE
importing wallets fails on Windows for paths containing spaces

### ISSUE THREAD

**Issue by dooglus** [nochowderforyou/clams#100]
I've seen many people complaining of an error trying to import their old wallets:

    CDB : Error 2, can't open database (code -1)

It turns out that this happens if there is a space in the pathname to the wallet they're importing. ".../Documents and Settings/..." for example.

Copying the wallet to C:\wallet.dat and importing from there fixes it.

I'm told the same issue happens using 'clamd importwallet' too, so it's not a Qt issue.

I've been unable to reproduce it on Linux.

**Comment by kwentzell** [comment]
I forgot to close this. The issue only exists on mac/nix now (why people/Apple use spaces in paths is beyond me).

**Comment by kwentzell** [comment]
The new issue is here: https://github.com/nochowderforyou/clams/issues/193

It's the same, I just thought this had been closed =p
