### ISSUE TITLE
error message mentions 'litecoin'

### ISSUE THREAD

**Issue by dooglus** [nochowderforyou/clams#131]
I saw this today:

    $ clamd sendtoaddress 
    error: {"code":-1,"message":"sendtoaddress <litecoinaddress> <amount> [comment] [comment-to] [tx-comment]\n<amount> is a real and is rounded to the nearest 0.000001"}

Checking the source I see two mentions of litecoin:

    rpcwallet.cpp:            "sendtoaddress <litecoinaddress> <amount> [comment] [comment-to] [tx-comment]\n"
    rpcwallet.cpp:            "sendfrom <fromaccount> <tolitecoinaddress> <amount> [minconf=1] [comment] [comment-to] [tx-comment]\n"

**Comment by l0rdicon** [comment]
This was updated in 1.4.4 and already fixed in master!  

https://github.com/nochowderforyou/clams/commit/1cf0908988a896894c2d8509b09d6825e6e8f61e
