### ISSUE TITLE
error building v1.4.4 on Linux

### ISSUE THREAD

**Issue by dooglus** [nochowderforyou/clams#132]
CXX      qt/qt_libbitcoinqt_a-qrcodedialog.o
    qt/qrcodedialog.cpp:12:22: fatal error: qrencode.h: No such file or directory
     #include <qrencode.h>
                          ^
    compilation terminated.

It appears I'm missing a library. Shouldn't the ./configure step detect this and either complain or just decide not to build the Qt version?

**Comment by l0rdicon** [comment]
Your correct. All my testing was done on computers with qr so I never saw this error.

It most likely does actually detect it correctly in configure. The include statement I believe needs to check if qr code is enabled and it isn't currently doing that.

I'll take a look at this today

**Comment by l0rdicon** [comment]
Its more then checking when to include the qrencode.h file. Currently if you don't include qr it will break QT building.  

Looks like there will be some re factoring involved.

**Comment by dooglus** [comment]
doc/build-unix.md says "This will build clam-qt as well if the dependencies are met"

If the dependencies are not met, for example if the QR lib isn't installed, then it should just not try to build the Qt version... problem solved. :)
