### ISSUE TITLE
is there a working testnet chain?

### ISSUE THREAD

**Issue by dooglus** [nochowderforyou/clams#134]
A while ago I tried connecting to the CLAM testnet but couldn't find any peers.

I don't know if there even is a testnet chain in existence, and if not how to go about starting one. I guess there's some proof of work that needs doing, and initial distribution.

It would be useful to have a testnet to try new releases against before switching to the new releases on the mainnet.

**Comment by l0rdicon** [comment]
There isn't no, and totally agree it would be useful. If not even a live testnet, something you can download to quickly setup a testnet locally between to clients.

To properly mimic the mainnet we need to have an initial dist. I had figured on creating maybe 10k addresses/outputs and publishing all the adrress details.

Its been in my head for a bit to do this but haven't got around. I'll see if I can make the push this weekend

**Comment by dooglus** [comment]
I think a 'real' testnet would be more useful. If a few people left testnet instances running, staking on their servers, we would be able to catch a lot more bugs before release than we are currently doing. I expect both the 'off by 10^8' difficulty bug from a few months back and the 'kill all the orphans' bug from 1.4.4 would have been detected before release if we had a realistic way of testing.

**Comment by l0rdicon** [comment]
I'm working on this. Will post a PR once I have a working testnet

**Comment by creativecuriosity** [comment]
https://github.com/nochowderforyou/clams/pull/230

Comments?

**Comment by creativecuriosity** [comment]
The recent merge https://github.com/nochowderforyou/clams/pull/233 has completed this task, and it can be closed, right?

**Comment by l0rdicon** [comment]
correct
