### ISSUE TITLE
typo in 'reason' string

### ISSUE THREAD

**Issue by dooglus** [nochowderforyou/clams#135]
In main.cpp:

    // Disallow large transaction comments
    if (tx.strCLAMSpeech.length() > MAX_TX_COMMENT_LEN) {
        reason = "tx-comment-to-large";

That should be "too" large.

Is the reason string used for anything that now expects it to be spelled that way, or can we fix it?

**Comment by l0rdicon** [comment]
Its not used as a check anywheres no. It can safely be changes to tx-comment-too-large

**Comment by dooglus** [comment]
I just fixed this, made a pull request, pulled it, looked for this issue and saw that it was closed already.

Did you mean to close it?

**Comment by dooglus** [comment]
Fixed in #144.
