### ISSUE TITLE
SEGV in Checkpoints::GetTotalBlocksEstimate() at first peer connect (testnet)

### ISSUE THREAD

**Issue by bluen** [nochowderforyou/clams#136]
Hi, 

A comment in the code (checkpoints.cpp - see below) states "TestNet has no checkpoints", but Checkpoints::GetTotalBlocksEstimate() does  `mapCheckpointsTestnet.rbegin()->first` - which dereferences the iterator returned by rbegin().
But: "If the container is empty, the returned iterator value shall not be dereferenced." 

I tried to run two instances of clamd (on two separate hosts) with "-testnet", and have one of
them connect to the other (with connect=.... or addnode=....). Both instances instantly crash
with a SIGSEGV after the version message is received.

This modification avoids the crash (by adding one checkpoint - the testnet genesis block):
```
diff --git a/src/checkpoints.cpp b/src/checkpoints.cpp
index 6d13ac6..3d32461 100644
--- a/src/checkpoints.cpp
+++ b/src/checkpoints.cpp
@@ -36,7 +36,10 @@ namespace Checkpoints
     ;
 
-    // TestNet has no checkpoints
-    static MapCheckpoints mapCheckpointsTestnet;
+    static MapCheckpoints mapCheckpointsTestnet =
+        boost::assign::map_list_of
+        ( 0,      hashGenesisBlockTestNet )
+    ;
      
 
     bool CheckHardened(int nHeight, const uint256& hash)
```  

I'm not sure if this is an appropriate solution - maybe simply checking if the map is empty and handle that case appropriately in the 3 occurrences of mapCheckpointsTestnet in checkpoints.cpp 
would be better...

Best regards

**Comment by creativecuriosity** [comment]
Eventually handled via: https://github.com/nochowderforyou/clams/pull/230
?

**Comment by bluen** [comment]
As far as I can see handled there.

**Comment by creativecuriosity** [comment]
It was a long time in coming; thanks for the good work :)
