### ISSUE TITLE
results of RPC 'importwallet' command written to terminal

### ISSUE THREAD

**Issue by dooglus** [nochowderforyou/clams#140]
From https://bitcointalk.org/index.php?topic=623147.msg10402427#msg10402427 :

clamd (headless) writes the results of the RPC 'importwallet' command to the terminal, rather than the log, even if it's backgrounded.

**Comment by l0rdicon** [comment]
The logging system was updated to use LogPrintf instead of printf and this function was missed in the merge. Changing it to LogPrintf will fix it

**Comment by dooglus** [comment]
Fixed in #146.
