### ISSUE TITLE
Restrict staking to outputs associated with a specific pubKey.

### ISSUE THREAD

**Issue by creativecuriosity** [nochowderforyou/clams#200]
I have received a request to support restricting staking to a specific address/pubKey.  This could possibly be implemented via a -stakeonly=pubKey flag?

**Comment by dooglus** [comment]
Yes, that would be easy enough to implement.

I guess it would be like -connect=<peer>, where you can specify it multiple times, once per address, and it adds that address to the ones that are allowed to stake, and if you don't specify any then there's no restriction.

**Comment by dooglus** [comment]
How's this?

I used:

    stake=xW1fBvmNw23fHLNVkcYoMDTF9m8uQgCLMk
    stake=xUQEspFX3pQYNEJwJ5zAkWxes7azQjkDSq

to mirror the 'connect=' option. It's not "-connectonly', just '-connect'.

**Comment by creativecuriosity** [comment]
Fermented, distilled and served for enjoyment at room temperature in a day.

With each of these commits, CLAM quickly becomes the most tweak-able and customizable stake system in the space.

Awesome ;D
