### ISSUE TITLE
error setting up gitian

### ISSUE THREAD

**Issue by dooglus** [nochowderforyou/clams#203]
gitian@chris:~/gitian-builder$ make -C ../clams/depends download SOURCES_PATH=`pwd`/cache/common
    make: Entering directory `/home/gitian/clams/depends'
    make[1]: Entering directory `/home/gitian/clams/depends'
    Fetching boost...
    2015-07-16 14:25:01 URL:http://sourceforge.net/ [639/639] -> "/home/gitian/clams/depends/work/download/boost-1_55_0/boost_1_55_0.tar.bz2.temp" [1]
    /home/gitian/clams/depends/work/download/boost-1_55_0/boost_1_55_0.tar.bz2.temp: FAILED
    sha256sum: WARNING: 1 computed checksum did NOT match
    make[1]: *** [/home/gitian/gitian-builder/cache/common/download-stamps/.stamp_fetched-boost-boost_1_55_0.tar.bz2] Error 1

**Comment by l0rdicon** [comment]
Is this from the build.log or are you running the commands yourself and not using the descriptors?

https://github.com/nochowderforyou/clams/blob/master/contrib/gitian-descriptors/gitian-win.yml

The command would be 

./bin/gbuild --commit clams=v${VERSION} ../clams/contrib/gitian-descriptors/gitian-win.yml        

You can find that in the release process 

https://github.com/nochowderforyou/clams/blob/master/doc/release-process.md
