### ISSUE TITLE
How was the original genesis block generated?

### ISSUE THREAD

**Issue by Jheguy2** [nochowderforyou/clams#214]
I'm trying to setup my own PoS network from scratch and I thought your coin would be a great place to start. However I do not see anywhere in the code that involves the generation of a genesis block. Has this code been removed or was the original genesis block generated through other methods? Any help would be greatly appreciated. Thank you.

**Comment by creativecuriosity** [comment]
Generating your genesis block is a sort of "right of passage".
An exhilarating experience that should not be robbed by hand holding, in my opinion.

[Link](http://lmgtfy.com/?q=generate+genesis+block)

**Comment by creativecuriosity** [comment]
I think Litecoin may have the generation code at least partly intact and commented out - if not, review other alternative codebases.

It is around.

**Comment by Jheguy2** [comment]
Ok thank you so much. I've checked pretty much every single source (see pic)
![ss 2015-08-19 at 01 59 25](https://cloud.githubusercontent.com/assets/6590510/9349591/2e6239d4-4616-11e5-808f-9f302c76f7fa.jpg)

but I'll try to add the generation code again. Can't thank you enough if that's what I'm doing wrong.

**Comment by Jheguy2** [comment]
I tried this python script originally:
https://github.com/lhartikk/GenesisH0
but I was unsure what hashing algorithm I should use since the coin is PoS.

**Comment by Jheguy2** [comment]
As well, the compiled daemon does not output to debug.log whenever the genesis data is changed. Is this something I have to enable before compiling?

**Comment by creativecuriosity** [comment]
The hashing algorithm is up to you.

Not sure I exactly understand the question concerning the debug.log file.

**Comment by Jheguy2** [comment]
Thank you, I made a mistake in my change and forgot to alter somewhere else in the code. Running sed on the entire directory solved my issue.

**Comment by creativecuriosity** [comment]
Since speed of the hashing algorithm is not designed to be a limiting factor for a Proof-of-Stake network; one might suggest the usage of the easiest to calculate hashing algorithm, likely SHA; unless you intend to require Proof-Of-Work in the implementation or to punish stakers for having a large set of outputs staking.

**Comment by Jheguy2** [comment]
Thanks man. The hash I'm running right now for the genesis block is scrypt since it was the fastest to generate with cpu. My plan was to use PoS for my testing but I'm not sure now how to generate the next block. Since the genesis block evaporates the first coins, there's no owners of the coins to generate blocks through PoS. Right now I'm just pointing a scrypt miner at my clamsd but none of my block attempts are getting accepted. Any advice?

**Comment by creativecuriosity** [comment]
Please change port and constants such that you do not disrupt the normal network as you test.  Further, you need to specify a period of PoW until you have mature coins to stake with; or use another work-around to bootstrap.

**Comment by Jheguy2** [comment]
All constants are changed and the entire setup is behind a non-WAN facing network. How is the period of PoW achieved? Is it specified through checkpoints?

**Comment by creativecuriosity** [comment]
if(nheight > X){ doPOS } else { doPOW }

**Comment by creativecuriosity** [comment]
Completed - Closing.
