### ISSUE TITLE
clam-qt crashes if you try to import a wallet that doesn't exist

### ISSUE THREAD

**Issue by dooglus** [nochowderforyou/clams#215]
* run qt/clam-qt
* click 'file'
* click 'import wallet'
* type a bunch of random letters
* hit return
* clam-qt crashes

![screenshot - 220815 - 03 11 54 am](https://cloud.githubusercontent.com/assets/573356/9423516/935fda5a-487b-11e5-8f2c-7bc451e0e5eb.png)

It appears to be an incorrectly handled exception:

    ************************
    EXCEPTION: St13runtime_error       
    CDB : Error 2, can't open database        
    clam in Runaway exception       

clamd on the other hand deals with it correctly:

    $ clamd importwallet /tmp/randomjunk
    error: {"code":-1,"message":"CDB : Error 2, can't open database "}

**Comment by kwentzell** [comment]
Fixed under Windows. 

Reopen the issue if it happens under another platform. I just have clamd compiled on Linux at the moment.
