### ISSUE TITLE
do we need a 'deleteprivkey' RPC command?

### ISSUE THREAD

**Issue by dooglus** [nochowderforyou/clams#220]
I recently wanted to move an address from one wallet to another. I can `dumpprivkey` and `importprivkey` to copy it, but don't know how to then delete it from the first wallet.

https://github.com/dooglus/clams/tree/deleteprivkey takes a stab at implementing a `deleteprivkey` RPC command. [If you remove a private key while running the QT interface it doesn't update the balance or transaction list until you restart.]

Is this worth merging? [How much work is it to fix the issue with QT not updating its display? Etc?]

**Comment by creativecuriosity** [comment]
Shoot-from-the-hip, uninformed guess; Possibly?
https://github.com/nochowderforyou/clams/blob/master/src/qt/walletmodel.cpp#L111

Might want to make sure we have copious warnings; and possibly rename to deleteprivkey.
I can see an uninformed user mucking about in the console and meeting doom.

I can see it being quite useful as well, however.

Just some thoughts.

**Comment by dooglus** [comment]
I fixed the QT issue, and renamed it to 'delete' instead of 'remove'.

I edited the description of the command:

            "Irreversibly deletes the private key corresponding to the given address from your wallet.\n"

Is that sufficient warning? Or what did you have in mind?

**Comment by creativecuriosity** [comment]
Merged. Closing.
