### ISSUE TITLE
Sync issue, discussion.

### ISSUE THREAD

**Issue by creativecuriosity** [nochowderforyou/clams#294]
https://github.com/nochowderforyou/clams/commit/66493570358a53f65b209590c38459cef92a0112  

The above commit touches much of the code I've been crawling in an attempt to identify the issue with syncing.  

@robvanmieghem  
Did you ever identify the issue you mentioned associated with this commit?  

@dooglus  
Thoughts on hashHighBlock?  
https://github.com/nochowderforyou/clams/blob/master/src/main.cpp#L3252  

The initial inventory message appears to get fulfilled/getblock'd just fine; on subsequent inventory messages something is triggering rampant duplicate 'already have' requests.  

Thoughts, anyone?

**Comment by creativecuriosity** [comment]
At minimum, the hashHighBlock check linked needs to be updated for testnet.

**Comment by l0rdicon** [comment]
sync issue is fixed in 2.1.0! closing
