### ISSUE TITLE
clamclient.com outdated

### ISSUE THREAD

**Issue by haraldg** [nochowderforyou/clams#297]
Not sure where to report this - looks like there is no contact information on the site.

Anyway clamclient.com/learn/market probably shouldn't recommend cryptsy anymore and Yacuna und bleutrade also look a bit dead at least.

**Comment by ClamProject** [comment]
The website is open source :)  
https://github.com/nochowderforyou/nochowderforyou.github.io

**Comment by haraldg** [comment]
Created a PR so closing this issue.
