### ISSUE TITLE
Request for documentation on wallet

### ISSUE THREAD

**Issue by abmohan** [nochowderforyou/clams#298]
Relative blockchain and CLAM novice here. 

I would really appreciate some documentation on how to do the following through the command line (assuming clamd has been running for a week or so, is up to date and has successfully dug a CLAM or two):

1. determine my wallet address(es)
2. determine how many CLAM coins I've successfully dug
3. send the CLAMs to another address

I see that all of this is possible through the Qt app, but cannot find any documentation to figure out how to do this through the command line. It seems like the creators of CLAM assume that the users of the clam daemon are already familiar with bitcoind

**Comment by kwentzell** [comment]
Running `clamd help` can give you a bunch of info on commands available for use. This is the real documentation.

1. As for this, it's not really possible to show all of your addresses(they change often), unless you use pywallet to read it.  To show all addresses with a balance, you can use `clamd listaddressgroupings`. You can also use `clamd getinfo` to show basic info on your wallet, such as being able to see the spendable vs. unspendable balance.

2. Unless you moved the coin, they should show up with the methods above. But to be sure, your entire wallet history can be found in debug.log in the ~/.clam directory. I can't remember the exact phrase, but try searching for a string like "dug" or "dig".

3. `clamd sendtoaddress <clam address> <amount>`

**Comment by ClamProject** [comment]
I would additionally point you towards the following clam.conf/execution flags:  
  
    -stakenotify=  
    -staketo=  
    -rewardto=  
  
https://github.com/nochowderforyou/clams/blob/master/src/init.cpp#L262  
https://github.com/nochowderforyou/clams/blob/master/src/init.cpp#L483  
https://github.com/nochowderforyou/clams/blob/master/src/init.cpp#L489  
The point concerning documentation is a reasonable complaint.

**Comment by dooglus** [comment]
> determine my wallet address(es)

There's `getaddressesbyaccount`, which will list all the receiving addresses for the given account, and `listaccounts`, which will list the accounts. If you've only used the default account then this will list all your receiving addresses:

    $ clamd getaddressesbyaccount ''

> determine how many CLAM coins I've successfully dug

I would use `listtransactions` to list all the transactions, and `grep` it for transactions giving you exactly 4.60545574 CLAMs.

> send the CLAMs to another address

You can use `sendfrom`, `sendmany`, or (`createrawtransaction`, `signrawtransaction`, `sendrawtransaction` in order)

**Comment by abmohan** [comment]
Thank you @kwentzell, @ClamProject and @dooglus for the responses. Much appreciated! 

@ClamProject - wasn't a complaint at all. I think the userbase you're targeting is largely familiar with bitcoind. Clams are my first foray into cryptocurrency, so still wrapping my head around the ecosystem. 

Thanks again!

**Comment by abmohan** [comment]
@ClamProject - had a follow up question regarding the execution flags. Do you guys have a sample `clam.conf` file with a `stakenotify` command?

At the moment, I've got something like this:

```
rpcuser=xyz
rpcpassword=pqr
stakenotify=python myscript '%a','%r'
```

Looking at my balance and at debug.log, it's clear that I've staked a new coin. However, my script doesn't seem to have run. 

Any thoughts?

**Comment by kwentzell** [comment]
I think we figured this on IRC. This should work as a config line: `stakenotify=python /home/user/myscript %r %a %t %s` 

There is also a test network which you can use to test parsing the blockchain at no expense. This wiki will help you get setup, it's definitely worth checking out. https://github.com/nochowderforyou/clams/wiki/Testnet

I can throw you a few test CLAMs when you get it working.

**Comment by abmohan** [comment]
Thanks, @kwentzell. It turns out that the single quotes I had in there were probably what caused it to fail. `stakenotify` indeed functions as expected. 

Thanks for the link to Testnet. That's very helpful! I'll be happy to get those test CLAMs from you once I get it up and running.
