### ISSUE TITLE
importprivkey and importwalletdump stopped working

### ISSUE THREAD

**Issue by doliver0** [nochowderforyou/clams#301]
I've tested this on Linux Mint 18 and Ubuntu 16.04 LTS. After importing private keys that have the distribution CLAMs available (I verified with /dig on Just-Dice), they don't show up in my balance. No transactions are showing either. Starting the client with -rescan does not fix this and -salvagewallet seems to just break everything entirely (wallet gets corrupted after using).

**Comment by kwentzell** [comment]
What address are you trying to dig? Is the wallet locked? What version of bdb are you using?

**Comment by doliver0** [comment]
I'm very sorry, I'm dumb and didn't realize there are both compressed and uncompressed versions of the private key and I was using the wrong one. Everything works as it's supposed to and I am closing the issue.

**Comment by creativecuriosity** [comment]
There are no dumb questions :)  
Even 'simple' questions can serve to help others in the future :)
