### ISSUE TITLE
khashier block explorer isn't updating

### ISSUE THREAD

**Issue by dooglus** [nochowderforyou/clams#305]
It looks like the CLAM client on khashier crashed 3 days ago.

I would restart it, but I don't know which one to use of these three:

    clams/current/src/clamd
    clams/l0rdicon/src/clamd
    clamsStake/clams/src/clamd

**Comment by l0rdicon** [comment]
it looks like the blockchain became corrupt. Working on restoring it now

**Comment by l0rdicon** [comment]
Its catching up now, not many blocks behind.  

clams/clamd  

is the one in use right now which is built from the current master. 

It was using the 2.0.0-rc but wouldn't sync after it died so I just moved to the current master and saved the blockchain / debug to take a look at.

**Comment by dooglus** [comment]
For the record I had the same problem with 2.0.0-rc. It corrupted both the blockchain and my wallet.dat. I nearly lost 10k CLAMs because of it, but luckily I was able to find the private key in the wallet 'by hand'.

**Comment by creativecuriosity** [comment]
Great.  
  
Do we have any idea _why_ it corrupted the chain/wallet?  
  
I assume this is re: https://github.com/nochowderforyou/clams/issues/303 ?

**Comment by l0rdicon** [comment]
That would be a correct assumption.  Exact same error as in #303
