### ISSUE TITLE
Please help me guys, Sync issues

### ISSUE THREAD

**Issue by LouVan** [nochowderforyou/clams#309]
I have a normal connection about 500-1mbs downloading files. But my Clams wallet sync really slow. My pc is 32 bit, and I already sync it about 3-4 days but not finished yet.
[Here](http://i.imgur.com/zX0ubAH.png)
Is it possible if someone upload it from c:/user/appdata/roaming/clam and I downloaded it to work my sycn?
Please help me guys.

**Comment by dooglus** [comment]
Try using a bootstrap.dat file:

https://bitcointalk.org/index.php?topic=623147.msg9772191#msg9772191

**Comment by LouVan** [comment]
So, I should download this right? bootstrap.dat ? The size is about 1.3 GB. 
Next, I open it or move it to c:/user/appdata/roaming/clam?
Thank you for your answer.

**Comment by accttotech** [comment]
Yeah put it in that folder, the samr one with the wallet.dat file, then and
restart... It should say "importing blocks".

--
Justin Abraham

**Comment by LouVan** [comment]
Thank you very much sir, I will try it later, hopefully it will works with my 32 bit.
Thanks again guys 👍 👍

**Comment by LouVan** [comment]
When I use bootsrap.dat, should I be connectiong to the internet or not?

**Comment by accttotech** [comment]
No, I don't think you need internet until after all of the data from the
bootstrap.dat file is imported.

--
Justin Abraham

**Comment by l0rdicon** [comment]
sync issues fixed in 2.1.0

**Comment by accttotech** [comment]
Took 1.5 years, but thank you !!!
--
Justin Abraham

**Comment by l0rdicon** [comment]
better late then never :P
