### ISSUE TITLE
Change Name to BitcoinLitecoinAndDogecoinButNotNecessarilyInThatOrderClams

### ISSUE THREAD

**Issue by junseth** [nochowderforyou/clams#312]
Given that BitcoinCash just forked, it seems clear to me that a chain that uses a chain state as the means of determining initial distribution of a coin is, indeed, a legitimate Bitcoin fork. While I understand that there might end up being great confusion with regard to which Bitcoin is to be used here or there, it also seems obvious to me that Clams is the longest running legitimate Bitcoin fork using the "state of the chain" (which would be a great name for a podcast) as a means for distribution.

As such, I think that Clams should consider changing its name to BitcoinClams, which will provide the longest running POS implementation of Bitcoin the legitimacy of the name, as well as emphasizing ClamCoins as an alternative to the disgusting censorship of Theymos and obvious collusion that Adam Back, his dark corporation Blockstreamm and the rest of the core team have had with Satan.

Alternatively, it might be worth considering that Clams, itself, be forked in much the same way that Clams was originally forked. We could copy the state of clams' blockchain and distribute more equitably the chains currency under the monkier "BitcoinClams" as proposed here, for the sake of better preserving the vision of our LORD and Savior Satoshi Nakamurmo.

Thank you for considering this proposal. I pray that the patron Saint of Blockchains, Saint Catherine, would heap upon your third eye the blessings you deserve for the open source work you have done unto Blockchain Jesus who is and was and is to come forever and ever. And in so considering this proposal, I would hope you give special consideration to all those in the Godhead of the Blockchain that you might not commit some Sebelianistically disparaging comment that would cause Him to unbless your work.

May you fork your mother if you want fork,

Junseth

**Comment by creativecuriosity** [comment]
All hail the Great CLAM; the alpha and omega of forkage.  
Closed for future merging and worship.

**Comment by junseth** [comment]
![Image of YUNOMerge](https://cdn.meme.am/cache/instances/folder53/500x/80085053/y-u-no-y-u-no-merge.jpg)

**Comment by dooglus** [comment]
Joshua, while I see the logic of your argument you must bear in mind that CLAM is just as much a fork of Litecoin and Dogecoin as it is of Bitcoin.

It doesn't seem fair to use "Bitcoin" in the name and not the other two. Or, for that matter, to put Bitcoin first.

How about we compromise and change the name to BitcoinLitecoinAndDogecoinButNotNecessarilyInThatOrderClams instead? A bit like how SegWit2X found a compromise between the people who don't want a hard fork and the people who don't want SegWit by giving everyone both things.

**Comment by junseth** [comment]
I think this sounds reasonable. Can we reopen this ticket under the title "Change Name to BitcoinLitecoinAndDogecoinButNotNecessarilyInThatOrderClams"?

**Comment by dooglus** [comment]
I changed the title, but I'm too scared of creativecuriosity to reopen it.

**Comment by accttotech** [comment]
Please leave this issue as closed.

Warmest Regards,
Justin Abraham

**Comment by YiumPotato** [comment]
I can see it happen.. CashMeClamside, coming to fruition. 

Hail The Clam Lords.
