### ISSUE TITLE
Problems with RC2

### ISSUE THREAD

**Issue by falsificado** [nochowderforyou/clams#318]
After installing, looks like the client does not connect to any peer at all. I had to add manually with addnode=xxx in clam.conf so it could connect to a node. Afer that, it works great. At the moment, i have 81 connected peers.

Additionally, it gives me a lot of 
`socket recv error 104`
in debug.log

**Comment by l0rdicon** [comment]
Rc2 has pretty much been abandoned. it for the most part works fine but I
have had problems with staking during testing.

I'm working on a different update that's much closer to bitcoin tip (few
hundred commits behind) but I haven't brought it over into a branch on
clams repo yet.

I got pos itself functioning ovet the night so it just a matter of pulling
in the clam specific code and testing.

I'm a few days from having it syncing on the clam network and then it's
going to replace rc2.

would love for you guys to start testing /using it once I get it over

**Comment by l0rdicon** [comment]
Closing issue, unrelated to client v2.1.0
