### ISSUE TITLE
clamd crashes (and freezes ubuntu EC2 box)

### ISSUE THREAD

**Issue by abmohan** [nochowderforyou/clams#322]
I'm trying to run clamd on Ubuntu 16.04 on EC2, and totally freezes the server. I restarted, tailed the logs and ran `nohup clamd &` and saw this error message materialize: 

> Bound to [::]:31174
> Bound to 0.0.0.0:31174
> init message: Loading block index...
> Opening LevelDB in /home/ubuntu/.clam/txleveldb
> Transaction index version is 70509
> Opened LevelDB successfully
> LoadBlockIndex(): hashBestChain=7304c02259a9451611e6e80c853bbc88163d2e19a0157e2c9d3d71e795a5e88f  height=1447956  trust=450074001804470332481  date=03/31/17 18:48:48
> LoadBlockIndex(): synchronized checkpoint 00000c3ce6b3d823a35224a39798eca9ad889966aeb5a9da7b960ffb9869db35
> Verifying last 500 blocks at level 1
>  block index           16036ms
> init message: Loading wallet...
> nFileVersion = 1041800
> Keys: 102 plaintext, 0 encrypted, 102 w/ metadata, 102 total
>  wallet                  317ms
> init message: Rescanning...
> Rescanning last 36 blocks (from block 1447920)...
>  rescan                    1ms
> 
> 
> ************************
> EXCEPTION: N5boost16exception_detail10clone_implINS0_19error_info_injectorINS_21thread_resource_errorEEEEE
> boost::thread_resource_error: Resource temporarily unavailable
> clam in AppInit()

Anyone else run into this?

**Comment by l0rdicon** [comment]
Closing issue, unrelated to client v2.1.0
