### ISSUE TITLE
Cannot validate block

### ISSUE THREAD

**Issue by falsificado** [nochowderforyou/clams#324]
I am using clam version v2.0.0.0-RC1 and i got a problem trying to sync blocks:

ERROR: CheckProofOfStake() : INFO: read txPrev failed
WARNING: ProcessBlock(): check proof-of-stake failed for block 83c145021fe99435eb7523a6d7d9b9088456c016036953ea8b442e4a84153687

And now i am stuck in block 2113202 while the older client is way ahead of this one

**Comment by ghost** [comment]
One thing to try. If you have a funded wallet, try MOVING it to one side and using a fresh empty wallet until the client is fully synced (you probably need to start from 0 again, a bootstrap.dat is useful) and then stop the client and switch back to the funded wallet. Sometime a client will attempt to stake before it is fully synced, causing a local (and unfortunately, permanent) hard fork.

**Comment by l0rdicon** [comment]
Closing issue, unrelated to client v2.1.0
