### ISSUE TITLE
protected function

### ISSUE THREAD

**Issue by nemetz** [nochowderforyou/clams#332]
I got an error while trying to compile:

`qt/optionsdialog.cpp: In constructor ‘OptionsDialog::OptionsDialog(QWidget*, bool)’:
qt/optionsdialog.cpp:125:47: error: ‘void GUIUtil::ItemDelegate::keyEscapePressed()’ is protected within this context
     connect(delegate, &GUIUtil::ItemDelegate::keyEscapePressed, this, &OptionsDialog::reject);
                                               ^~~~~~~~~~~~~~~~
In file included from qt/optionsdialog.cpp:13:0:
qt/guiutil.h:266:12: note: declared protected here
       void keyEscapePressed();
            ^~~~~~~~~~~~~~~~
qt/optionsdialog.cpp:125:93: error: no matching function for call to ‘OptionsDialog::connect(GUIUtil::ItemDelegate*&, void (GUIUtil::ItemDelegate::*)(), OptionsDialog*, void (QDialog::*)())’
 egate, &GUIUtil::ItemDelegate::keyEscapePressed, this, &OptionsDialog::reject);`

Avoided by commenting the following line in qt/optionsdialog.cpp:

`connect(delegate, &GUIUtil::ItemDelegate::keyEscapePressed, this, &OptionsDialog::reject);`

Or passing the flag --with-gui=no while running ./configure

Looks like some sort of protected function being called, but the function in the class is public:

`class ItemDelegate : public QItemDelegate
  {
      Q_OBJECT
  public:
      ItemDelegate(QObject* parent) : QItemDelegate(parent) {}

  Q_SIGNALS:
      void keyEscapePressed();

  private:
      bool eventFilter(QObject *object, QEvent *event);
  };
} // namespace GUIUtil`

I dont really know how to fix it, any hints?

**Comment by l0rdicon** [comment]
Closing issues related to 1.4.17 to focus on the new client v2.1.0
