### ISSUE TITLE
expose 'split' and 'merge' in GUI

### ISSUE THREAD

**Issue by dooglus** [nochowderforyou/clams#50]
The client will currently split an output if it stakes within 28 hours of its most recent transaction (previous stake, or previous movement) regardless of the size of the output. It could be a tiny output that just happened to get lucky. I would argue that such an output doesn't need splitting.

It will also re-merge those split outputs the next time either of them stakes if they are both less than 1000 CLAMs.

This results in split - merge - split - merge cycles.

The re-merging is particularly annoying, since it destroys the age of two outputs at once, while only providing a single reward.

We should:

1) make the split and merge happen based on output size and current difficulty, rather than the random luck of a particular output

2) expose the thresholds for split and merge (however the end up after 1) above) in the GUI and RPC interface

3) set reasonable defaults - probably with 'merge' disabled by default

**Comment by creativecuriosity** [comment]
Merging the GUI exposure part of this issue into https://github.com/nochowderforyou/clams/issues/208.

Closing.
